# Generated by Django 4.0.4 on 2022-06-02 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('End_time', models.DateTimeField(null=True)),
                ('Tag', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Working', 'Working'), ('Done', 'Done'), ('Overdue', 'Overdue')], default='OPEN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='todol',
        ),
    ]
