# Generated by Django 4.0.4 on 2022-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_delete_todol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='End_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
